sudo: false
language: node_js
node_js:
  - 12
  - 14
cache:
  directories:
    - node_modules
    - ./data-provider/node_modules
matrix:
    include:
        - env: TARGET=data-provider
        - env: TARGET=status-web
script: 
  - cd $TARGET
  - yarn test
  - yarn build
