sudo: false
language: node_js
node_js:
  - 16
cache:
  directories:
    - node_modules
matrix:
    include:
        - env: TARGET=packages/data-provider
        - env: TARGET=packages/status-web
script: 
  - cd $TARGET
  - npm install
  - npm run build
  - npm run test
