version: "3"

services:

  status-web:
    build:
      context: ./packages/status-web
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      - ./packages/status-web:/usr/app
      - ./packages/status-web/node_modules:/usr/app/node_modules
      - ./packages/status-web/.next:/usr/app/.next
    ports: 
      - 3000:3000

  data-provider: 
    build:
      context: ./packages/data-provider
    #  dockerfile: Dockerfile.dev
    volumes:
    - './data:/usr/app/data'
    #  - ./packages/data-provider:/usr/app
    #  - /usr/app/node_modules
    ports: 
      - 4001:3000

