version: "3"

services:

  dataProvider:
    restart: unless-stopped
    labels:
      description: "Data Provider Service"
    depends_on: 
      - kousa

  web:
    restart: unless-stopped
    labels:
      description: "Website Service"
    depends_on: 
      - dataProvider
      


