version: "3"

# service_name:
#   build: 
#     context: .
#     dockerfile: path/to/Dockerfile
#

services:

  status-web:
    build: ./packages/status-web
    ports: 
      - 3000:3000

  data-provider:
    build: ./packages/data-provider
    ports: 
      - 4001:3000

