version: "3"

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    labels:
      description: "RabbitMQ broker"
    # volumes:
    #   - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
    #   - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 60s
      timeout: 5s

  data-provider:
    restart: unless-stopped
    labels:
      description: "Data Provider Service"
    depends_on: 
      - rabbitmq

  status-web:
    restart: unless-stopped
    labels:
      description: "Website Service"
    depends_on: 
      - data-provider
      - rabbitmq
      


