version: "3"

services:

  data-provider:
    restart: unless-stopped
    labels:
      description: "Data Provider Service"

  status-web:
    restart: unless-stopped
    labels:
      description: "Website Service"
    depends_on: 
      - data-provider
      


