version: "3"

services:

  status-web:
    build: ./packages/status-web
    stdin_open: true
    ports: 
      - 3000:3000

  data-provider: 
    build:
      context: ./packages/data-provider
      dockerfile: Dockerfile.dev
    volumes:
      - './packages/data-provider:/usr/app'
      - './data:/usr/app/data'
      - /usr/app/node_modules
    ports: 
      - 4001:3000

